services:
  - type: web
    name: minio-test
    runtime: docker

    plan: free

    envVars:
      - key: MINIO_ROOT_USER
        value: admin

      - key: MINIO_ROOT_PASSWORD
        value: Strong@password123